services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # environment:
      # - VITE_API_URL=https://internstreetph.site/api
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      # - PORT=3000
      - NODE_ENV=development
      # - SUPABASE_URL=${SUPABASE_URL}
    command: ["npm", "start"]
    depends_on:
      - frontend