services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
      # - VITE_API_URL=http://localhost:3000
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - API_URL=${API_URL}
      # - API_URL=http://localhost:3000
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - RDS_DB_HOST=${RDS_DB_HOST}
      - DB_PORT=${DB_PORT}
    command: ["npm", "start"]
    depends_on:
      - frontend